version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: fastapi_app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend
    volumes:
      - ./app:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
